services:
  api_fastapi: #postgres: # name of 1st services
    container_name: container_api_image # define the name of container for this service
    image: api_image # define the container image
    restart: always
    #environment: # define environment variable
    #  POSTGRESS_USER: username
    #  POSTGRESS_PASSWORD: password
    #  POSTGRESS_DB: demo_db # create database by default
    ports: # to expose the container port
      - "8001:8001"
    volumes: # path to persist evriything we want
      - api_fastapi:/var/lib/api_fastapi/data
    networks: # to make connection with anothers containers
      api_frontend_network: # network name
        ipv4_address: 192.168.1.2  # Assign a specific IP address 
  
  frontend_streamlit_app: #spring-boot-app:
    container_name: container_frontend_app_image
    image: frontend_app_image
    restart: always
    ports:
      - "8501:8501"
    volumes: # path to persist evriything we want
      - frontend_streamlit_app:/var/lib/frontend_streamlit_app/data
    networks:
      api_frontend_network: # network name must be the same in containers we want to connect 
        ipv4_address: 192.168.1.3  # Assign a different IP address
    depends_on: # to specify that this container will begin to run if "postgres" is finish to run
      - api_fastapi

# to specify place we want to persist trafic, data, ... on container 
volumes:
  api_fastapi:
  frontend_streamlit_app:

# networks make link between multiples containers
networks: # This is the key indicating the start of the network configuration section in a Docker Compose file.
  api_frontend_network: # This is the name given to the network
    driver: bridge # This specifies that the network is a bridge network wich allows containers to communicate with each other using container names as hostnames.
    ipam: # This stands for IP Address Management. It allows you to specify the IP addressing configuration for the network.
      driver: default # This specifies the default IPAM driver to be used. The default driver is sufficient for many use cases.
      config: # This is where you define the IP address configuration for the network.
        - subnet: 192.168.1.0/24 # This defines the subnet that will be used by the containers in this network. In this case, it's 192.168.1.0/24, which means the network can use IP addresses ranging from 192.168.1.1 to 192.168.1.254.
          gateway: 192.168.1.254 # This specifies the gateway IP address for the network. The gateway is typically the first IP address in the subnet