# name of your CICD code
name: Build API with docker

# # when or what event needs for begin running the code
# on:
#   push:
#     branches:
#       - main
#       - 'releases/**'

# when or what event needs for begin running the code
on:
  # push:
  #   branches:
  #     - main_dev
  pull_request:
    branches:
      - main
  # schedule: # frequence to launch actions. see this link https://crontab.guru/
  #   - cron: "0 0 * * 1" # at 00:00 on Monday

# jobs you want to run
jobs:
  API-docker-actions:
    # name: Run API - Windows # define the name of job
    # runs-on: windows-latest # define the machine where the code will run, Windows here   
    # services:
    #   registry:
    #     image: registry:2
    #     ports:
    #       - 5000:5000

    name: Run API - Linux # define the name of job
    runs-on: ubuntu-latest # define the machine where the code will run, Lunix here  
    # services:
    #   registry:
    #     image: registry:2
    #     ports:
    #       - 5000:5000

    # name: Run API - Macos # define the name of job
    # runs-on: macos-latest # define the machine where the code will run, MacOS here
    # services:
    #   registry:
    #     image: registry:2
    #     ports:
    #       - 5000:5000

    steps:
      - name: checkout code 
        uses: actions/checkout@v4 # define action to run at the step "checkout code", action can bee found on https://github.com/marketplace/actions

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: ./api_docker
          file: ./api_docker/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api_image:latest # localhost:5000/my-base-image:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push images into Docker Hub 
        uses: docker/build-push-action@v5
        with:
          context: ./api_docker
          dockerfile: Dockerfile 
          push: true 
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api_image:latest
