# name of your CICD code
name: Build docker images and docker compose
# when or what event needs for begin running the code
on:
  pull_request:
    branches:
      - main

# jobs you want to run
jobs:
  API-docker-image-actions:
    name: Run API - Linux # define the name of job
    runs-on: ubuntu-latest # define the machine where the code will run, Lunix here  

    steps:
      - name: checkout code 
        uses: actions/checkout@v4 # define action to run at the step "checkout code", action can bee found on https://github.com/marketplace/actions

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: ./api_docker
          platforms: linux/amd64, linux/arm64
          file: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api_image:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push images into Docker Hub 
        uses: docker/build-push-action@v5
        with:
          context: ./api_docker
          platforms: linux/amd64, linux/arm64
          file: Dockerfile 
          push: true 
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api_image:latest
